import { computed, nextTick, ref, shallowRef } from 'vue';
import type { RouteRecordRaw } from 'vue-router';
import { defineStore } from 'pinia';
import { useBoolean } from '@sa/hooks';
import type { CustomRoute, ElegantConstRoute, LastLevelRouteKey, RouteKey, RouteMap } from '@elegant-router/types';
import { router } from '@/router';
import { fetchGetConstantRoutes, fetchGetUserRoutes, fetchIsRouteExist } from '@/service/api';
import { SetupStoreId } from '@/enum';
import { createStaticRoutes, getAuthVueRoutes } from '@/router/routes';
import { ROOT_ROUTE } from '@/router/routes/builtin';
import { getRouteName, getRoutePath } from '@/router/elegant/transform';
import { useAuthStore } from '../auth';
import { useTabStore } from '../tab';
import {
  filterAuthRoutesByRoles,
  getBreadcrumbsByRoute,
  getCacheRouteNames,
  getGlobalMenusByAuthRoutes,
  getSelectedMenuKeyPathByKey,
  isRouteExistByRouteName,
  sortRoutesByOrder,
  transformMenuToSearchMenus,
  updateLocaleOfGlobalMenus
} from './shared';

export const useRouteStore = defineStore(SetupStoreId.Route, () => {
  const authStore = useAuthStore();
  const tabStore = useTabStore();
  const { bool: isInitConstantRoute, setBool: setIsInitConstantRoute } = useBoolean();
  const { bool: isInitAuthRoute, setBool: setIsInitAuthRoute } = useBoolean();

  /**
   * Auth route mode
   *
   * It recommends to use static mode in the development environment, and use dynamic mode in the production
   * environment, if use static mode in development environment, the auth routes will be auto generated by plugin
   * "@elegant-router/vue"
   */
  const authRouteMode = ref(import.meta.env.VITE_AUTH_ROUTE_MODE);

  /** Home route key */
  const routeHome = ref(import.meta.env.VITE_ROUTE_HOME);

  /**
   * Set route home
   *
   * @param routeKey Route key
   */
  function setRouteHome(routeKey: LastLevelRouteKey) {
    routeHome.value = routeKey;
  }

  /** constant routes */
  const constantRoutes = shallowRef<ElegantConstRoute[]>([]);

  function addConstantRoutes(routes: ElegantConstRoute[]) {
    const constantRoutesMap = new Map<string, ElegantConstRoute>([]);

    routes.forEach(route => {
      constantRoutesMap.set(route.name, route);
    });

    constantRoutes.value = Array.from(constantRoutesMap.values());
  }

  /** auth routes */
  const authRoutes = shallowRef<ElegantConstRoute[]>([]);

  function addAuthRoutes(routes: ElegantConstRoute[]) {
    const authRoutesMap = new Map<string, ElegantConstRoute>([]);

    routes.forEach(route => {
      authRoutesMap.set(route.name, route);
    });

    authRoutes.value = Array.from(authRoutesMap.values());
  }

  const removeRouteFns: (() => void)[] = [];

  /** Global menus */
  const menus = ref<App.Global.Menu[]>([]);
  const searchMenus = computed(() => transformMenuToSearchMenus(menus.value));

  /** Get global menus */
  function getGlobalMenus(routes: ElegantConstRoute[]) {
    menus.value = getGlobalMenusByAuthRoutes(routes);
  }

  /** Update global menus by locale */
  function updateGlobalMenusByLocale() {
    menus.value = updateLocaleOfGlobalMenus(menus.value);
  }

  /** Cache routes */
  const cacheRoutes = ref<string[]>([]);

  /**
   * Exclude cache routes
   *
   * for reset route cache
   */
  const excludeCacheRoutes = ref<string[]>([]);

  /**
   * Get cache routes
   *
   * @param routes Vue routes
   */
  function getCacheRoutes(routes: RouteRecordRaw[]) {
    cacheRoutes.value = getCacheRouteNames(routes);

    // menu-bridge 是所有动态菜单页面的宿主组件，必须加入缓存列表
    // KeepAlive 的 include 按组件 name 匹配，而动态路由名（如 dyn_2035）与组件名不一致
    if (!cacheRoutes.value.includes('menu-bridge')) {
      cacheRoutes.value.push('menu-bridge');
    }
  }

  /**
   * Reset route cache
   *
   * @default router.currentRoute.value.name current route name
   * @param routeKey
   */
  async function resetRouteCache(routeKey?: RouteKey | string) {
    const routeName = routeKey || (router.currentRoute.value.name as RouteKey);

    excludeCacheRoutes.value.push(routeName as string);

    // 动态菜单路由的组件名是 menu-bridge，需一并排除才能清除缓存
    if (String(routeName).startsWith('dyn_')) {
      excludeCacheRoutes.value.push('menu-bridge');
    }

    await nextTick();

    excludeCacheRoutes.value = [];
  }

  /** Global breadcrumbs */
  const breadcrumbs = computed(() => getBreadcrumbsByRoute(router.currentRoute.value, menus.value));

  /** Reset store */
  async function resetStore() {
    const routeStore = useRouteStore();

    routeStore.$reset();

    resetVueRoutes();

    // after reset store, need to re-init constant route
    await initConstantRoute();
  }

  /** Reset vue routes */
  function resetVueRoutes() {
    removeRouteFns.forEach(fn => fn());
    removeRouteFns.length = 0;
  }

  /** init constant route */
  async function initConstantRoute() {
    if (isInitConstantRoute.value) return;

    const staticRoute = createStaticRoutes();

    if (authRouteMode.value === 'static') {
      addConstantRoutes(staticRoute.constantRoutes);
    } else {
      const { data, error } = await fetchGetConstantRoutes();

      if (!error) {
        addConstantRoutes(data);
      } else {
        // if fetch constant routes failed, use static constant routes
        addConstantRoutes(staticRoute.constantRoutes);
      }
    }

    handleConstantAndAuthRoutes();

    setIsInitConstantRoute(true);

    tabStore.initHomeTab();
  }

  /** Init auth route */
  async function initAuthRoute() {
    // check if user info is initialized
    if (!authStore.userInfo.userId) {
      await authStore.initUserInfo();
    }

    if (authRouteMode.value === 'static') {
      initStaticAuthRoute();
    } else {
      await initDynamicAuthRoute();
    }

    tabStore.initHomeTab();
  }

  /** Init static auth route */
  function initStaticAuthRoute() {
    const { authRoutes: staticAuthRoutes } = createStaticRoutes();
    const backendMenuRoutes = createBackendMenuRoutes((authStore.userInfo as Record<string, any>).menus || []);

    if (authStore.isStaticSuper) {
      addAuthRoutes([...staticAuthRoutes, ...backendMenuRoutes]);
    } else {
      const filteredAuthRoutes = filterAuthRoutesByRoles(staticAuthRoutes, authStore.userInfo.roles);

      if (filteredAuthRoutes.length > 0) {
        addAuthRoutes([...filteredAuthRoutes, ...backendMenuRoutes]);
      } else {
        const fallbackHome = staticAuthRoutes.find(route => route.name === 'home');
        const fallbackRoutes = fallbackHome ? [fallbackHome, ...backendMenuRoutes] : backendMenuRoutes;
        addAuthRoutes(fallbackRoutes);
      }
    }

    handleConstantAndAuthRoutes();

    setIsInitAuthRoute(true);
  }

  /** Build elegant routes from backend first/second menus returned by auth/getUserInfo */
  function createBackendMenuRoutes(rawMenus: any[]): ElegantConstRoute[] {
    if (!Array.isArray(rawMenus) || rawMenus.length === 0) {
      return [];
    }

    // 一级菜单图标映射
    const zhTitleIconMap: Record<string, string> = {
      系统管理: 'mdi:settings',
      管理信息: 'mdi:database',
      人员管理: 'mdi:account-heart',
      收入成本: 'mdi:cash',
      经营分析: 'mdi:chart-line'
    };

    const routes: ElegantConstRoute[] = [];
    const usedNames = new Set<string>();

    rawMenus.forEach((menu1, menu1Index) => {
      const parentName = buildUniqueFirstLevelRouteName(
        `dyn${normalizeRouteName(menu1?.name || `menu_${menu1Index + 1}`).replace(/_/g, '')}`,
        usedNames
      );
      const childrenRaw = Array.isArray(menu1?.children) ? menu1.children : [];

      const children: ElegantConstRoute[] = childrenRaw.map((menu2: any, menu2Index: number) => {
        const funcCode = String(menu2?.functionCode || `func_${menu1Index + 1}_${menu2Index + 1}`);
        const childName = buildUniqueRouteName(`dyn_${normalizeRouteName(funcCode)}`, usedNames);
        const childPath = `/dynamic-menu/${encodeURIComponent(funcCode)}`;

        return {
          name: childName,
          path: childPath,
          component: 'view.menu-bridge',
          props: true,
          meta: {
            title: String(menu2?.name || `菜单${menu2Index + 1}`),
            i18nKey: '',
            icon: 'mdi:menu-right-outline',
            order: Number(menu2?.order) || menu2Index + 1,
            hideInMenu: false,
            multiTab: true,
            keepAlive: true,
            query: [
              { key: 'functionCode', value: funcCode },
              { key: 'menu1', value: String(menu1?.name || '') },
              { key: 'menu2', value: String(menu2?.name || '') },
              { key: 'module', value: String(menu2?.module || '') },
              { key: 'params', value: String(menu2?.params || '') },
              { key: 'frontendRoute', value: String(menu2?.frontendRoute || '') }
            ],
            functionCode: funcCode,
            menu1: String(menu1?.name || ''),
            menu2: String(menu2?.name || ''),
            module: String(menu2?.module || ''),
            params: String(menu2?.params || ''),
            frontendRoute: String(menu2?.frontendRoute || '')
          } as any
        } as ElegantConstRoute;
      });

      if (children.length === 0) {
        return;
      }

      // 获取一级菜单的图标
      const menuTitle = String(menu1?.name || '动态菜单');
      const menuIcon = zhTitleIconMap[menuTitle] || 'mdi:folder-outline';

      routes.push({
        name: parentName,
        path: `/dynamic/${encodeURIComponent(menuTitle)}`,
        component: 'layout.base',
        meta: {
          title: menuTitle,
          icon: menuIcon,
          order: Number(menu1?.order) || menu1Index + 100,
          hideInMenu: false
        },
        children
      } as ElegantConstRoute);
    });

    return routes;
  }

  function normalizeRouteName(value: string) {
    const normalized = value
      .toLowerCase()
      .replace(/[^a-z0-9_]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '');

    return normalized || 'route';
  }

  function buildUniqueRouteName(base: string, usedNames: Set<string>) {
    if (!usedNames.has(base)) {
      usedNames.add(base);
      return base;
    }

    let index = 2;
    let candidate = `${base}_${index}`;
    while (usedNames.has(candidate)) {
      index += 1;
      candidate = `${base}_${index}`;
    }

    usedNames.add(candidate);
    return candidate;
  }

  function buildUniqueFirstLevelRouteName(base: string, usedNames: Set<string>) {
    const normalizedBase = base.replace(/_/g, '') || 'dynroute';

    if (!usedNames.has(normalizedBase)) {
      usedNames.add(normalizedBase);
      return normalizedBase;
    }

    let index = 2;
    let candidate = `${normalizedBase}v${index}`;
    while (usedNames.has(candidate)) {
      index += 1;
      candidate = `${normalizedBase}v${index}`;
    }

    usedNames.add(candidate);
    return candidate;
  }

  /** Init dynamic auth route */
  async function initDynamicAuthRoute() {
    const { data, error } = await fetchGetUserRoutes();

    if (!error) {
      const { routes, home } = data;

      addAuthRoutes(routes);

      handleConstantAndAuthRoutes();

      setRouteHome(home);

      handleUpdateRootRouteRedirect(home);

      setIsInitAuthRoute(true);
    } else {
      // if fetch user routes failed, reset store
      authStore.resetStore();
    }
  }

  /** handle constant and auth routes */
  function handleConstantAndAuthRoutes() {
    const allRoutes = [...constantRoutes.value, ...authRoutes.value];

    const sortRoutes = sortRoutesByOrder(allRoutes);

    const vueRoutes = getAuthVueRoutes(sortRoutes);

    resetVueRoutes();

    addRoutesToVueRouter(vueRoutes);

    getGlobalMenus(sortRoutes);

    getCacheRoutes(vueRoutes);
  }

  /**
   * Add routes to vue router
   *
   * @param routes Vue routes
   */
  function addRoutesToVueRouter(routes: RouteRecordRaw[]) {
    routes.forEach(route => {
      const removeFn = router.addRoute(route);
      addRemoveRouteFn(removeFn);
    });
  }

  /**
   * Add remove route fn
   *
   * @param fn
   */
  function addRemoveRouteFn(fn: () => void) {
    removeRouteFns.push(fn);
  }

  /**
   * Update root route redirect when auth route mode is dynamic
   *
   * @param redirectKey Redirect route key
   */
  function handleUpdateRootRouteRedirect(redirectKey: LastLevelRouteKey) {
    const redirect = getRoutePath(redirectKey);

    if (redirect) {
      const rootRoute: CustomRoute = { ...ROOT_ROUTE, redirect };

      router.removeRoute(rootRoute.name);

      const [rootVueRoute] = getAuthVueRoutes([rootRoute]);

      router.addRoute(rootVueRoute);
    }
  }

  /**
   * Get is auth route exist
   *
   * @param routePath Route path
   */
  async function getIsAuthRouteExist(routePath: RouteMap[RouteKey]) {
    const routeName = getRouteName(routePath);

    if (!routeName) {
      return false;
    }

    if (authRouteMode.value === 'static') {
      const { authRoutes: staticAuthRoutes } = createStaticRoutes();
      return isRouteExistByRouteName(routeName, staticAuthRoutes);
    }

    const { data } = await fetchIsRouteExist(routeName);

    return data;
  }

  /**
   * Get selected menu key path
   *
   * @param selectedKey Selected menu key
   */
  function getSelectedMenuKeyPath(selectedKey: string) {
    return getSelectedMenuKeyPathByKey(selectedKey, menus.value);
  }

  async function onRouteSwitchWhenLoggedIn() {
    // some global init logic when logged in and switch route
  }

  async function onRouteSwitchWhenNotLoggedIn() {
    // some global init logic if it does not need to be logged in
  }

  return {
    resetStore,
    routeHome,
    menus,
    searchMenus,
    updateGlobalMenusByLocale,
    cacheRoutes,
    excludeCacheRoutes,
    resetRouteCache,
    breadcrumbs,
    initConstantRoute,
    isInitConstantRoute,
    initAuthRoute,
    isInitAuthRoute,
    setIsInitAuthRoute,
    getIsAuthRouteExist,
    getSelectedMenuKeyPath,
    onRouteSwitchWhenLoggedIn,
    onRouteSwitchWhenNotLoggedIn
  };
});
