/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  common: () => import("@/views/common/index.vue"),
  contract: () => import("@/views/contract/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "menu-bridge": () => import("@/views/menu-bridge/index.vue"),
  "permission-demo": () => import("@/views/permission-demo/index.vue"),
  "room-status": () => import("@/views/room-status/index.vue"),
  personnel_employee: () => import("@/views/personnel/employee/index.vue"),
  personnel_interview: () => import("@/views/personnel/interview/index.vue"),
  personnel_invitation: () => import("@/views/personnel/invitation/index.vue"),
  personnel_train: () => import("@/views/personnel/train/index.vue"),
  "room-status": () => import("@/views/room-status/index.vue"),
  system_dept: () => import("@/views/system/dept/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
