# Virtual Hosts
#
# Required modules: mod_log_config

# If you want to maintain multiple domains/hostnames on your
# machine you can setup VirtualHost containers for them. Most configurations
# use only name-based virtual hosts so the server doesn't need to worry about
# IP addresses. This is indicated by the asterisks in the directives below.
#
# Please see the documentation at 
# <URL:http://httpd.apache.org/docs/2.4/vhosts/>
# for further details before you try to setup virtual hosts.
#
# You may use the command line option '-S' to verify your virtual host
# configuration.


# Add any other Virtual Hosts below
<Directory "${DOCROOT}/htdocs">
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<VirtualHost *:80>
    ServerAdmin admin@www.localhost
    DocumentRoot "${DOCROOT}/htdocs"
    ServerName localhost
    ErrorLog "${DOCROOT}/logs/www.localhost-error.log"
    CustomLog "${DOCROOT}/logs/www.localhost-access.log" common
</VirtualHost>

<Directory "${DOCROOT}/oa">
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<VirtualHost *:80>
    ServerAdmin admin@oa.localhost
    DocumentRoot "${DOCROOT}/oa/public"
    ServerName oa.localhost
    ErrorLog "${DOCROOT}/logs/oa.localhost-error.log"
    CustomLog "${DOCROOT}/logs/oa.localhost-access.log" common
</VirtualHost>

<Directory "D:/code/php/mis/backend/public">
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<VirtualHost *:80>
    ServerAdmin admin@mis.localhost
    ServerName mis.localhost
    DocumentRoot "D:/code/php/mis/backend/public"
    ErrorLog "D:/code/php/mis/logs/mis.localhost-error.log"
    CustomLog "D:/code/php/mis/logs/mis.localhost-access.log" common
</VirtualHost>
